### PR TITLE
Add relative coordinate support to the createfromcoords command

### PR DESCRIPTION
**Pull request by Bluebotlabz**
A few small changes
- Implement relative coordinate support to the create portal command
- Change the removeportal command to default to remove both portals unless removeDestination is explicitly stated as false
- Copy config.yml to defaultConfig.yml
- Add invalid coordinate error to the create portal command
- Edit .gitignore to support some development environments

### CODE REVIEW

**Comment by Bluebotlabz** [comment]
Please do review the code as I haven't developed for Spigot/Bukkit before and there could be some obvious mistakes in there

**Comment by Lauriethefish** [comment]
Gonna make a few changes.

**Comment by Lauriethefish** [comment]
An issue right now is that the `/bp createfromcoords` command now always requires a player. Ideally we'd only want it to require a player when using relative coordinates (with a correct error message automatically generated)

**Comment by Bluebotlabz** [comment]
Ok, this is something I can work on

**Comment by Lauriethefish** [comment]
No it's fine, I'm about to do a lot of other changes that will cause a merge nightmare.

**Comment by Bluebotlabz** [comment]
oh, ok

in the meantime, I'm going to be doing my best trying to figure out how to get command completion hints to work lol

(not even the example code is working for commodore lol)

**Comment by Bluebotlabz** [comment]
Also, I would probably recomment editing the readme to say Java 16 since both arrow case statements and a few other features are not supported in Java 8

**Comment by Lauriethefish** [comment]
Oh yeah, sorry I bumped the java version a week or so ago and forgot to update it.

**Comment by Lauriethefish** [comment]
Changes made, doing some testing now. Essentially, with these changes, the relative coordinates can be directly passed to the command as parameters, e.g. 
```java
public boolean createFromCoordinates(CommandSender sender,
                                         World originWorld,
                                         Vector originCorner1,
                                         Vector originCorner2,
                                         World destWorld,
                                         Vector destCorner1,
                                         Vector destCorner2,
                                         String twoWayStr,
                                         String invertStr,
                                         String name
                                         ```

**Comment by Lauriethefish** [comment]
I hope you'll agree that it looks a little neater now.

**Comment by Bluebotlabz** [comment]
From the code, it _should_ work, I'm testing it now

**Comment by Lauriethefish** [comment]
I changed boolean parsing to make the `/bp remove` a little simpler.
Now the only accepted values are `yes`, `no`, `true` and `false`, all other values being rejected with an error message.

**Comment by Lauriethefish** [comment]
@Bluebotlabz Any progress with completion hints or should I go ahead and merge this?

**Comment by Bluebotlabz** [comment]
If anything I've made negative progress, feel free to merge this, I'll make a pull request if I ever figure out command completion

**Pull request merged**
